export type SupplyInvoiceData = {
  companyName: string;
  reference: string;
  batchNumber: string;
  batchNumberDisplay: string;
  procurementDate: string;
  statusLabel: string;
  showPricing: boolean;
  supplierName: string;
  supplierCode: string;
  supplierAddress: string | null;
  supplierPhone: string | null;
  procurementTypeLabel: string;
  productType: string;
  productConditionLabel: string | null;
  productAgeLabel: string | null;
  productColorLabel: string | null;
  mixedTypeLabel: string | null;
  numberOfBags: number;
  kgPerBag: number | null;
  extraKg: number;
  totalKg: number;
  unitPrice: number | null;
  totalValue: number | null;
  qualityDecisionLabel: string;
  paymentStatusLabel: string;
  approvedByName: string | null;
  approvedAtLabel: string | null;
  notes: string | null;
  generatedAtLabel: string;
};
